"Resource/UI/HudTournamentSetup.res"
{
    "HudTournamentSetupBG"
    {
        "ControlName"    "ImagePanel"
        "fieldName"      "HudTournamentSetupBG"
        "xpos"           "0"
        "ypos"           "0"
        "zpos"           "-1"
        "wide"           "180"
        "tall"           "65"
        "autoResize"     "0"
        "pinCorner"      "0"
        "visible"        "1"
        "enabled"        "1"
        "fillcolor"      "sh_black_transparent"
    }
    "TournamentSetupLabel"
    {
        "ControlName"    "Label"
        "fieldName"      "TournamentLabel"
        "font"           "HudFontSmallBold"
        "xpos"           "9999"
    }
    "TournamentTeamNameLabel"
    {
        "ControlName"    "Label"
        "fieldName"      "TournamentTeamNameLabel"
        "font"           "HudFontSmallest"
        "xpos"           "9999"
    }
    "TournamentNameEdit"
    {
        "ControlName"                    "TextEntry"
        "fieldName"                      "TournamentNameEdit"
        "xpos"                           "8"
        "ypos"                           "27"
        "wide"                           "120"
        "tall"                           "16"
        "autoResize"                     "0"
        "pinCorner"                      "0"
        "visible"                        "1"
        "enabled"                        "1"
        "tabPosition"                    "0"
        "textHidden"                     "0"
        "editable"                       "1"
        "maxchars"                       "5"
        "NumericInputOnly"               "0"
        "unicode"                        "0"
        "wrap"                           "0"
        "fgcolor_override"               "sh_white"
        "bgcolor_override"               "sh_dark_grey"
        "selectionColor_override"        "sh_button_armed"
        "selectionTextColor_override"    "sh_black"
        "labelText"                      "%teamname%"
        "textAlignment"                  "west"
    }
    "HudTournamentNameBG"
    {
        "ControlName"    "CTFImagePanel"
        "fieldName"      "HudTournamentNameBG"
        "xpos"           "9999"
    }
    "TournamentNotReadyButton"
    {
        "ControlName"                  "CExButton"
        "fieldName"                    "TournamentNotReadyButton"
        "xpos"                         "8"
        "ypos"                         "46"
        "wide"                         "70"
        "tall"                         "14"
        "zpos"                         "0"
        "autoResize"                   "0"
        "pinCorner"                    "2"
        "visible"                      "1"
        "enabled"                      "1"
        "labelText"                    "Not Ready"
        "textAlignment"                "center"
        "dulltext"                     "0"
        "brighttext"                   "0"
        "command"                      "teamnotready"
        "default"                      "1"
        "font"                         "HudFontSmallestBold"
        "fgcolor"                      "Red"
        "defaultBgColor_override"      "sh_black"
        "defaultFgColor_override"      "sh_white"
        "armedBgColor_override"        "sh_team_red"
        "armedFgColor_override"        "sh_white"
        "depressedBgColor_override"    "sh_team_red"
        "depressedFgColor_override"    "sh_white"
    }
    "TournamentReadyButton"
    {
        "ControlName"                  "CExButton"
        "fieldName"                    "TournamentReadyButton"
        "xpos"                         "96"
        "ypos"                         "46"
        "wide"                         "70"
        "tall"                         "14"
        "zpos"                         "0"
        "autoResize"                   "0"
        "pinCorner"                    "2"
        "visible"                      "1"
        "enabled"                      "1"
        "labelText"                    "Ready"
        "textAlignment"                "center"
        "dulltext"                     "0"
        "brighttext"                   "0"
        "command"                      "teamready"
        "default"                      "1"
        "font"                         "HudFontSmallestBold"
        "fgcolor"                      "FooterBGBlack"
        "defaultBgColor_override"      "sh_black"
        "defaultFgColor_override"      "sh_white"
        "armedBgColor_override"        "CreditsGreen"
        "armedFgColor_override"        "sh_white"
        "depressedBgColor_override"    "CreditsGreen"
        "depressedFgColor_override"    "sh_white"
    }
}
